version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://100.115.79.13:5000
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://madhusanka:hi4fdP5pn8dcwGFv@cluster0.0a4mi.mongodb.net/
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
      - CORS_ORIGIN=http://100.115.79.13:3000
    networks:
      - app-network
    restart: unless-stopped

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 